parameters:
#    project_common.example.class: Project\CommonBundle\Example

services:
#    project_common.example:
#        class: %project_common.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
